### ISSUE TITLE
liberation: ModuleNotFoundError: No module named 'fontTools'

### ISSUE THREAD

**Issue by simonbcn** [julroy67/kagayaki#12]
```
==> Making package: ttf-liberation-kagayaki 2.00.3-1 (Tue Mar  7 15:24:21 CET 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found 7c0f88d.zip
  -> Found 86fda57.zip
  -> Found 40-liberation.conf
==> Validating source files with md5sums...
    7c0f88d.zip ... Passed
    86fda57.zip ... Passed
    40-liberation.conf ... Passed
==> Extracting sources...
  -> Extracting 7c0f88d.zip with bsdtar
  -> Extracting 86fda57.zip with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 16:38 CET 24-Dec-2016-ML-D.
 Based on source from git with hash: 
Generating ttf from src/LiberationMono-Regular.sfd
Generating ttf from src/LiberationMono-Bold.sfd
Generating ttf from src/LiberationMono-Italic.sfd
Generating ttf from src/LiberationMono-BoldItalic.sfd
Generating ttf from src/LiberationSans-Regular.sfd
Generating ttf from src/LiberationSans-Bold.sfd
Generating ttf from src/LiberationSans-Italic.sfd
Generating ttf from src/LiberationSans-BoldItalic.sfd
Generating ttf from src/LiberationSerif-Regular.sfd
Generating ttf from src/LiberationSerif-Bold.sfd
Generating ttf from src/LiberationSerif-Italic.sfd
Generating ttf from src/LiberationSerif-BoldItalic.sfd
Traceback (most recent call last):
  File "scripts/setisFixedPitch-fonttools.py", line 31, in <module>
    from fontTools import ttLib
ModuleNotFoundError: No module named 'fontTools'
make: *** [Makefile:59: ttf-dir] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by simonbcn** [comment]
It still fails to me:
```
...
Generating ttf from src/LiberationMono-Regular.sfd
Generating ttf from src/LiberationMono-Bold.sfd
Generating ttf from src/LiberationMono-Italic.sfd
Generating ttf from src/LiberationMono-BoldItalic.sfd
Generating ttf from src/LiberationSans-Regular.sfd
Generating ttf from src/LiberationSans-Bold.sfd
Generating ttf from src/LiberationSans-Italic.sfd
Generating ttf from src/LiberationSans-BoldItalic.sfd
Generating ttf from src/LiberationSerif-Regular.sfd
Generating ttf from src/LiberationSerif-Bold.sfd
Generating ttf from src/LiberationSerif-Italic.sfd
Generating ttf from src/LiberationSerif-BoldItalic.sfd
Traceback (most recent call last):
  File "scripts/setisFixedPitch-fonttools.py", line 31, in <module>
    from fontTools import ttLib
ModuleNotFoundError: No module named 'fontTools'
make: *** [Makefile:59: ttf-dir] Error 1
```

I have to change the PKGBUILD: python-fonttools (no python2-...).
